# -*- coding: utf-8 -*-
"""fibonacci_series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S-lk-GVXUYkQBHyeYJpxWHf1SjtAwgQt
"""

n=int(input("enter the number of elements: "))
a=0
b=1
print(a)
print(b)

for i in range(0,n-2):
  c=a+b
  a=b
  b=c
  print(c)